// apps/web/src/components/Cartao.vue
<script setup lang="ts">
defineProps<{
  titulo: string;
}>();
</script>

<template>
  <section class="cartao">
    <h2>{{ titulo }}</h2>
    <slot />
  </section>
</template>

<style scoped>
.cartao {
  padding: var(--espaco-lg);
  background: var(--cor-superficie);
  border: 1px solid var(--cor-borda);
  border-radius: var(--raio-lg);
  box-shadow: var(--sombra-cartao);
}

h2 {
  margin-top: 0;
  font-size: var(--fonte-lg);
}
</style>

// apps/web/src/components/Cartao.tsx
import type { ReactNode } from 'react';

interface CartaoProps {
  titulo: string;
  children: ReactNode;
}

export function Cartao({ titulo, children }: CartaoProps) {
  return (
    <section
      style={{
        background: 'var(--cor-superficie)',
        border: '1px solid var(--cor-borda)',
        borderRadius: 'var(--raio-lg)',
        boxShadow: 'var(--sombra-cartao)',
        padding: 'var(--espaco-lg)',
      }}
    >
      <h2 style={{ fontSize: 'var(--fonte-lg)', marginTop: 0 }}>{titulo}</h2>
      {children}
    </section>
  );
}
